### PR TITLE
App.help_format initial commit.

### PR DESCRIPTION
**Pull request by BrianPugh**
Introduces the field `App.help_format` that indicates the markup language used within the docstring. This impacts how the help-page is rendered.

Addresses #81.

### CODE REVIEW

**Comment by Skyler-Altol** [comment]
@BrianPugh could we possibly make the default format for help strings be just pure text as it is in most libraries? ReST is still around for sure, but in terms of the most common defaults, straight text would be the most intuitive thing to default to, with the clear option to enable ReST or markdown if the developer desires those formats.

**Comment by BrianPugh** [comment]
I think either RST or markdown interprets general plaintext in a prettier way than interpreting the docstring content as-is (plaintext).

Consider the following short program:
```python
from cyclopts import App

app = App(help_format="rst")  # new default behavior


@app.default
def default():
    """My application summary.

    This is a pretty standard docstring; if there's a really long sentence
    I should probably wrap it because people don't like code that is more
    than 80 columns long.

    In this new paragraph, I would like to discuss the benefits of relaxing 80 cols to 120 cols.
    """


app()
```

and the console output:
```console
$ python my-script.py --help
Usage: default COMMAND

My application summary.

This is a pretty standard docstring; if there's a really long sentence I should probably wrap it because
people don't like code that is more than 80 columns long.

In this new paragraph, I would like to discuss the benefits of relaxing 80 cols to 120 cols.

╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────╮
│ --help,-h  Display this message and exit.                                                            │
│ --version  Display application version.                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

If we change the `docstring_format="plaintext"`:

```console
$ python my-script.py --help
Usage: default COMMAND

My application summary.

This is a pretty standard docstring; if there's a really long sentence
I should probably wrap it because people don't like code that is more
than 80 columns long.

In this new paragraph, I would like to discuss the benefits of relaxing 80 cols to 120 cols.

╭─ Commands ───────────────────────────────────────────────────────────────────────────────────────────╮
│ --help,-h  Display this message and exit.                                                            │
│ --version  Display application version.                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

For this reason, I think `markdown` or `rst` is a reasonable default. However, because we're dealing with _python_ docstrings, `rst` is the more reasonable default choice (I personally like using markdown better, but when in Rome).

**Comment by BrianPugh** [comment]
I opened up some PRs (#6 #7 #8) for [rich-rst](https://github.com/wasi-master/rich-rst/pulls). I'd like to see if they get merged.

**Comment by BrianPugh** [comment]
If my rich-rst PRs don't get merged in over the next few days, I can just vendor the rich-rst code into Cyclopts; the licenses are compatible.

**Comment by BrianPugh** [comment]
@wasi-master thanks for merging in the rich-rst PRs!

**Pull request merged**
