### PR TITLE
Bugfix/version help format

### PR DESCRIPTION
**Pull request by BrianPugh**
Applies the designated `App.help_format` to the `App.version` when calling `App.version_print()`.

@glenfletcher can you see if this fixes the bug for you? Thanks!

Addresses #187 .

### CODE REVIEW

**Comment by glenfletcher** [comment]
It doesn't appear to work; I added it to my project by installing it as a git submodule and doing an editable install via pip as follows (I've include the output of my version command):

```bash
$ git submodule add https://github.com/BrianPugh/cyclopts.git thirdparty/cyclopts
Cloning into '/home/glen/code/tools/schematalyst/thirdparty/cyclopts'...
remote: Enumerating objects: 2720, done.
remote: Counting objects: 100% (1698/1698), done.
remote: Compressing objects: 100% (655/655), done.
remote: Total 2720 (delta 1209), reused 1406 (delta 1039), pack-reused 1022
Receiving objects: 100% (2720/2720), 2.41 MiB | 6.29 MiB/s, done.
Resolving deltas: 100% (1991/1991), done.
$ cd thirdparty/cyclopts/
branch 'bugfix/version-help-format' set up to track 'origin/bugfix/version-help-format'.
Switched to a new branch 'bugfix/version-help-format'
$ gh pr checkout 188
$ pip install -e .
Obtaining file:///home/glen/code/tools/schematalyst/thirdparty/cyclopts
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: attrs>=23.1.0 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from cyclopts==2.7.1.post2+8101299) (23.2.0)
Requirement already satisfied: docstring-parser<0.16,>=0.15 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from cyclopts==2.7.1.post2+8101299) (0.15)
Requirement already satisfied: rich>=13.6.0 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from cyclopts==2.7.1.post2+8101299) (13.7.1)
Requirement already satisfied: rich-rst<2.0.0,>=1.3.1 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from cyclopts==2.7.1.post2+8101299) (1.3.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from cyclopts==2.7.1.post2+8101299) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from rich>=13.6.0->cyclopts==2.7.1.post2+8101299) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from rich>=13.6.0->cyclopts==2.7.1.post2+8101299) (2.18.0)
Requirement already satisfied: docutils in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from rich-rst<2.0.0,>=1.3.1->cyclopts==2.7.1.post2+8101299) (0.21.2)
Requirement already satisfied: mdurl~=0.1 in /home/glen/code/tools/schematalyst/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.6.0->cyclopts==2.7.1.post2+8101299) (0.1.2)
Building wheels for collected packages: cyclopts
  Building editable for cyclopts (pyproject.toml) ... done
  Created wheel for cyclopts: filename=cyclopts-2.7.1.post2+8101299-py3-none-any.whl size=8484 sha256=173c4a42055257a1ffb8108676448a2da8f3fe98e17f7f0cefe7fa43ba2f7c5b
  Stored in directory: /tmp/pip-ephem-wheel-cache-zi9sj_5u/wheels/a8/8f/51/05be6e1a15daa243af5c547376de6f38132c4320340fd37bf4
Successfully built cyclopts
Installing collected packages: cyclopts
  Attempting uninstall: cyclopts
    Found existing installation: cyclopts 2.7.1
    Uninstalling cyclopts-2.7.1:
      Successfully uninstalled cyclopts-2.7.1
Successfully installed cyclopts-2.7.1.post2+8101299

[notice] A new release of pip is available: 23.2.1 -> 24.1
[notice] To update, run: pip install --upgrade pip
$ cd ../..
$ schematalyst --version
[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]m[/red][bright_yellow]a[/bright_yellow][bright_green]t[/bright_green][bright_cyan]a[/bright_cyan][red]l[/red][brigh
t_yellow]y[/bright_yellow][bright_green]s[/bright_green][bright_cyan]t[/bright_cyan][/bold] [bold bright_white]v0.0.0[/bold bright_white]
```

I'm creating the CLI application using:

```py
cli = cyclopts.App(
    version=f"[bold]{__rich_app_name__}[/bold] [bold bright_white]v{__version__}[/bold bright_white]",
)
```

I also invoked the CLI app as a Python module in debugging mode using PyCharm, to verify it was calling into the installed submodule, and inspect the call to `print_version` I got the following

```
Stack:
version_print, core.py:399
__call__, core.py:818
<module>, __main__.py:8
<frame not available>
<frame not available>
Inspector:
console = {NoneType} None
self = {App} App(version='[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]...mands', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None), validator=[])
 config = {tuple: 0} ()
 console = {NoneType} None
 converter = {NoneType} None
 default_command = {NoneType} None
 default_parameter = {NoneType} None
 group = {tuple: 0} ()
 group_arguments = {Group} Group(name='Arguments', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None)
 group_commands = {Group} Group(name='Commands', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None)
 group_parameters = {Group} Group(name='Parameters', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None)
 help = {str} ''
 help_flags = {tuple: 2} ('--help', '-h')
 help_format = {NoneType} None
 meta = {App} App(version='0.0.0', version_flags=('--version',), help_flags=('--help', '-h'), group=(), group_arguments=Group(name='Argument...mands', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None), validator=[])
 name = {tuple: 1} ('_pydevd_bundle',)
 show = {bool} True
 usage = {NoneType} None
 validator = {list: 0} []
 version = {str} '[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]m[/red][bright_yellow]a[/bright_yellow][bright_green]t[/bright_green][bright_cyan]a[/bright_cyan][red]l[/red][bright_yellow]y[/bright_yellow][
 version_flags = {tuple: 1} ('--version',)
----
Stack:
version_print, core.py:400
__call__, core.py:818
<module>, __main__.py:8
<frame not available>
<frame not available>
Inspector:
console = {Console} <console width=80 None>
 color_system = {NoneType} None
 encoding = {str} 'utf-8'
 file = {TextIOWrapper} <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
 height = {int} 25
 highlighter = {ReprHighlighter} <rich.highlighter.ReprHighlighter object at 0x7f4b6b5cb110>
 is_alt_screen = {bool} False
 is_dumb_terminal = {bool} False
 is_interactive = {bool} False
 is_jupyter = {bool} False
 is_terminal = {bool} False
 legacy_windows = {bool} False
 no_color = {bool} False
 options = {ConsoleOptions} ConsoleOptions(size=ConsoleDimensions(width=80, height=25), legacy_windows=False, min_width=1, max_width=80, is_terminal=False, encoding='utf-8', max_height=25, justify=None, overflow=None, no_wrap=False, highlight=None, markup=None, height=None)
 quiet = {bool} False
 record = {bool} False
 safe_box = {bool} True
 size = {ConsoleDimensions: 2} ConsoleDimensions(width=80, height=25)
 soft_wrap = {bool} False
 stderr = {bool} False
 style = {NoneType} None
 tab_size = {int} 8
 width = {int} 80
self = {App} App(version='[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]...mands', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None), validator=[])
----
Stack:
version_print, core.py:408
__call__, core.py:818
<module>, __main__.py:8
<frame not available>
<frame not available>
Inspector:
console = {Console} <console width=80 None>
 color_system = {NoneType} None
 encoding = {str} 'utf-8'
 file = {TextIOWrapper} <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
 height = {int} 25
 highlighter = {ReprHighlighter} <rich.highlighter.ReprHighlighter object at 0x7f4b6b5cb110>
 is_alt_screen = {bool} False
 is_dumb_terminal = {bool} False
 is_interactive = {bool} False
 is_jupyter = {bool} False
 is_terminal = {bool} False
 legacy_windows = {bool} False
 no_color = {bool} False
 options = {ConsoleOptions} ConsoleOptions(size=ConsoleDimensions(width=80, height=25), legacy_windows=False, min_width=1, max_width=80, is_terminal=False, encoding='utf-8', max_height=25, justify=None, overflow=None, no_wrap=False, highlight=None, markup=None, height=None)
 quiet = {bool} False
 record = {bool} False
 safe_box = {bool} True
 size = {ConsoleDimensions: 2} ConsoleDimensions(width=80, height=25)
 soft_wrap = {bool} False
 stderr = {bool} False
 style = {NoneType} None
 tab_size = {int} 8
 width = {int} 80
help_format = {str} 'restructuredtext'
self = {App} App(version='[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]...mands', help='', _show=None, _sort_key=<NO_USER_SORT_KEY>, converter=None, validator=(), default_parameter=None), validator=[])
version_formatted = {RestructuredText} <rich_rst.RestructuredText object at 0x7f4b6b6b4ce0>
 code_theme = {str} 'monokai'
 default_lexer = {str} 'python'
 filename = {str} '<rst-document>'
 guess_lexer = {bool} False
 log_errors = {bool} True
 markup = {str} '[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]m[/red][bright_yellow]a[/bright_yellow][bright_green]t[/bright_green][bright_cyan]a[/bright_cyan][red]l[/red][bright_yellow]y[/bright_yellow][
version_raw = {str} '[bold][red]S[/red][bright_yellow]c[/bright_yellow][bright_green]h[/bright_green][bright_cyan]e[/bright_cyan][red]m[/red][bright_yellow]a[/bright_yellow][bright_green]t[/bright_green][bright_cyan]a[/bright_cyan][red]l[/red][bright_yellow]y[/bright_yellow][
```

Using my patched print_version from my issue:
```py
class App(cyclopts.App):
    def version_print(self) -> None:
        """Print the application version."""
        console = self._resolve_console(None, None)
        console.print(self.version() if callable(self.version) else self.version)


cli = App(
    version=f"[bold]{__rich_app_name__}[/bold] [bold bright_white]v{__version__}[/bold bright_white]",
)
```

I get the following expected output:
screenshot

I am not sure why your code isn't working the same as mine; I checked the console I get when debugging my version its:
```
console = {Console} <console width=80 None>
 color_system = {NoneType} None
 encoding = {str} 'utf-8'
 file = {TextIOWrapper} <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
 height = {int} 25
 highlighter = {ReprHighlighter} <rich.highlighter.ReprHighlighter object at 0x7f92f971b170>
 is_alt_screen = {bool} False
 is_dumb_terminal = {bool} False
 is_interactive = {bool} False
 is_jupyter = {bool} False
 is_terminal = {bool} False
 legacy_windows = {bool} False
 no_color = {bool} False
 options = {ConsoleOptions} ConsoleOptions(size=ConsoleDimensions(width=80, height=25), legacy_windows=False, min_width=1, max_width=80, is_terminal=False, encoding='utf-8', max_height=25, justify=None, overflow=None, no_wrap=False, highlight=None, markup=None, height=None)
 quiet = {bool} False
 record = {bool} False
 safe_box = {bool} True
 size = {ConsoleDimensions: 2} ConsoleDimensions(width=80, height=25)
 soft_wrap = {bool} False
 stderr = {bool} False
 style = {NoneType} None
 tab_size = {int} 8
 width = {int} 80
```

I'm not noticing a difference there

**Comment by glenfletcher** [comment]
I just tested the new commit in my project, and it works when `help_format` is set to rich.

I suggest adding an extra option, `version_format`, which defaults to `help_format` so an application can use differing help and version formats.

```py
# based on resolve_help_format, assumes version_format is defined the same as help_format
# then this function can be used instead of resolve_help_format in print_version
def resolve_version_format(app_chain: Optional[Iterable["App"]]) -> str:
    # Resolve version_format; None fallsback to parent; non-None overwrites parent.
    version_format = resolve_help_format(app_chain)
    if app_chain is None:
        return version_format
    for app in app_chain:
        if app.version_format is not None:
            version_format = app.version_format
    return version_format
```

**Comment by BrianPugh** [comment]
Added the proposed `App.version_format` in [5897fbd](https://github.com/BrianPugh/cyclopts/pull/188/commits/5897fbd95710985b32a667ac63ec4c69929a1157), what do you think?

**Comment by glenfletcher** [comment]
It looks good, I tested the the following:

```py
cli = cyclopts.App(
    version=f"[bold]{__rich_app_name__}[/bold] [bold bright_white]v{__version__}[/bold bright_white]",
    help_format="markdown",
    version_format="rich"
)
```

Which correctly formatted the version string using rich markup, while using markdown for the help messages.

The only comments I have remaining are non-critical stylistic and code quality nick-picking:

- In `version_print` `help_format = resolve_version_format([self])` the variable should be `version_fromat` for clarity.
- In the documentation for `version_format` while it correct, it should probably be written the be the same as for `help_format` for the fallback explanation i.e.
  ```rst
  If :obj:`None`, fallback to parenting :attr:`~.App.version_format`.
  If no :attr:`~.App.version_format` is defined, falls back to resolved :attr:`~.App.help_format`.
  ```
- Finally, the tests you added do not cover all possible scenarios, though the main missing test would be that `version_format` is correctly overriding `help_format`.

**Comment by BrianPugh** [comment]
Thanks for the feedback! Addressed in subsequent commits. I'm going to merge this and cut a release.

**Pull request merged**
